spring:
  datasource:
    #url: jdbc:mysql://172.21.108.151:3306/icondb?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mysql://192.168.1.11:3306/icondb?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Springbootplus679!
    driver-class-name: com.mysql.cj.jdbc.Driver

my-resouce-config:
  build_type: home
