server:
  port: ${PORT:11400}

spring:
  application:
    name: articleservice     # 将在 Eureka 注册的服务的逻辑名称
  profiles:
    active: dev
  servlet:
    multipart:
      # 上传一个文件最大值,默认1Mb
      max-file-size: 5MB
      # 上传多个文件最大值,50Mb,默认10Mb
      max-request-size: 50MB

eureka:
  instance:
    preferIpAddress: true   #注册服务的 IP 而不是服务器名称。
  client:
    registerWithEureka: true
    fetchRegistry: true     #下拉注册信息并复制一份到本地
    serviceUrl:
      defaultZone: ${EUREKASERVER_URI:http://localhost:8761/eureka/}
