server:
  port: ${PORT:11300}

spring:
  application:
    name: userservice     # 将在 Eureka 注册的服务的逻辑名称
  profiles:
    active: dev
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/jarticle?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC}
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    preferIpAddress: true   #注册服务的 IP 而不是服务器名称。
  client:
    registerWithEureka: true
    fetchRegistry: true     #下拉注册信息并复制一份到本地
    serviceUrl:
      defaultZone: ${EUREKASERVER_URI:http://localhost:8761/eureka/}
