version: '3.1'

services:

  user-cli:
    build: ./user-cli
    environment:
      MICRO_REGISTRY: "mdns"

  article-service:
    build: ./article-service
    environment:
      MICRO_REGISTRY: "mdns"

  email-service:
    build: ./email-service
    environment:
      MICRO_REGISTRY: "mdns"
      MQ_USER: "admin"
      MQ_PASSWORD: "admin"
      MQ_HOST: "rabbitmq"
      MQ_PORT: "5672"
      MQ_VHOST: "/"

  web-app:
    build: ./web-app
    ports:
      - 8080:8080

  user-service:
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      MQ_USER: "admin"
      MQ_PASSWORD: "admin"
      MQ_HOST: "rabbitmq"
      MQ_PORT: "5672"
      MQ_VHOST: "/"
    depends_on:
      - database

  # datastore:
  #   image: mongo
  #   ports:
  #     - 27017:27017

  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
    restart: always
    environment:
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
