version: '3.1'

services:

  eureka:
    build: ./eureka-service
    ports:
      - 8761:8761
    environment:
      PORT: "8761"
      PROFILE: "dev"

  zuul:
    build: ./zuul
    ports:
      - 11111:11111
    links:
      - eureka
    environment:
      PORT: "11111"
      PROFILE: "dev"
      EUREKA_SERVER: "eureka"
      EUREKASERVER_PORT: "8761"
      EUREKASERVER_URI: "http://eureka:8761/eureka/"

  article:
    build: ./article-service
    links:
      - eureka
    environment:
      PORT: "11400"
      PROFILE: "dev"
      EUREKA_SERVER: "eureka"
      EUREKASERVER_PORT: "8761"
      EUREKASERVER_URI: "http://eureka:8761/eureka/"

  user:
    build: ./user-service
    links:
      - eureka
    environment:
      PORT: "11300"
      PROFILE: "dev"
      EUREKA_SERVER: "eureka"
      EUREKASERVER_PORT: "8761"
      EUREKASERVER_URI: "http://eureka:8761/eureka/"
      DB_URL: "jdbc:mysql://database:3306/jarticle?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
      RABBITMQ_USER_NAME: "admin"
      RABBITMQ_PASSWORD: "admin"
      RABBITMQ_VIRTUAL_HOST: "/"
      RABBITMQ_HOST_NAME: "rabbitmq"
      RABBITMQ_PORT_NUMBER: "5672"

    links:
      - eureka
      - database
      - rabbitmq
    depends_on:
      - database
      - rabbitmq

  database:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    environment:
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
