version: '3.1'

services:

  eureka:
    build: ./eureka-service
    ports:
      - 8761:8761
    environment:
      PORT: "8761"
      PROFILE: "dev"

  zuul:
    build: ./zuul
    ports:
      - 11111:11111
    links:
      - eureka
    environment:
      PORT: "11111"
      PROFILE: "dev"
      EUREKA_SERVER: "eureka"
      EUREKASERVER_PORT: "8761"
      EUREKASERVER_URI: "http://eureka:8761/eureka/"

  article:
    build: ./article-service
    links:
      - eureka
    environment:
      PORT: "11400"
      PROFILE: "dev"
      EUREKA_SERVER: "eureka"
      EUREKASERVER_PORT: "8761"
      EUREKASERVER_URI: "http://eureka:8761/eureka/"

  user:
    build: ./user-service
    links:
      - eureka
    environment:
      PORT: "11300"
      PROFILE: "dev"
      EUREKA_SERVER: "eureka"
      EUREKASERVER_PORT: "8761"
      EUREKASERVER_URI: "http://eureka:8761/eureka/"
